export class Job {
  constructor(
  	public id: number,
  	public reservationTitle: string,
		public workAddress: string,
		public city: string,
		public state: string,
		public zip: string,
		public firstName: string,
		public lastName: string,
		public phone: string,
		public email: string,
		public company: string,
  	public singleRooms: Array<any>,
    public doubleRooms: Array<any>,
  	public status: string,
  	public internet: boolean,
  	public breakfast: boolean,
  	public kitchenette: boolean,
  	public restaurant: boolean,
  	public pets: boolean,
  	public shuttle: boolean,
  	public gym: boolean,
  	public walkingDistance: boolean,
  	public pool: boolean,
  	public notes: string,
  	public urgency: string,
  	public billableTo: string,
  	public projectNumber: string,
  	public projectType: string
	) { }
}